"""add system to task_attempt

Revision ID: b586f6b11458
Revises: f8f0da49b405
Create Date: 2026-03-01 00:53:44.341089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b586f6b11458'
down_revision = 'f8f0da49b405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_attempts', schema=None) as batch_op:
        batch_op.drop_column('system')

    # ### end Alembic commands ###
